services:
  wamf:
    container_name: wamf
    restart: unless-stopped
    image: ghcr.io/wamf-project/wamf:latest
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./media:/app/media
    ports:
      - 7767:7767 # The container port must match webui.port in config.yml.
    environment:
      TZ: Europe/London
